name: Build and test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.5
      - run: yarn install --frozen-lockfile --check-files
      - run: yarn run typecheck
      - run: yarn run build
